"""
CloudSight AI — Recommendation Domain Models

Pydantic models for optimization recommendations, savings summaries,
forecast results, and FinOps scoring.

Schemas align with:
- API-Specification.yaml (Recommendation, ForecastResponse, ScoreResponse)
- Recommendation-Rules.md (Sections 8–11)
"""

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from analytics.models.resource import ConfidenceScore, RiskLevel


# ---------------------------------------------------------------------------
# Recommendation Category — Recommendation-Rules.md §10
# ---------------------------------------------------------------------------

class RecommendationCategory(str, Enum):
    """Category for organizing recommendations by business impact.

    Categories (per Recommendation-Rules.md §10):
        QUICK_WIN:  LOW risk AND annual_savings < $2,000
        HIGH_IMPACT: annual_savings > $10,000
        STRATEGIC:  Reserved Capacity, Lifecycle Policies, Long-Term
    """
    QUICK_WIN = "QUICK_WIN"
    HIGH_IMPACT = "HIGH_IMPACT"
    STRATEGIC = "STRATEGIC"


# ---------------------------------------------------------------------------
# Recommendation — API-Specification.yaml + Recommendation-Rules.md
# ---------------------------------------------------------------------------

class Recommendation(BaseModel):
    """A single optimization recommendation.

    Represents an actionable, explainable cost-saving recommendation
    generated by one of the analytics engines. Includes risk assessment,
    confidence scoring, savings estimates, and executive explanations.

    Attributes:
        id:                     Unique recommendation identifier.
        resource_id:            ID of the resource being optimized.
        resource_type:          Service type (EC2, S3, EBS, RDS).
        title:                  Short recommendation title.
        reason:                 Technical justification.
        risk:                   Risk classification (LOW/MEDIUM/HIGH/BLOCKED).
        confidence:             Confidence score with label.
        monthly_savings:        Estimated monthly savings ($).
        annual_savings:         Estimated annual savings ($).
        implementation_steps:   Ordered steps to implement.
        executive_explanation:  Business-friendly explanation.
        category:               Quick Win / High Impact / Strategic.
        rule_id:                Source rule ID (e.g., EC2-001).
    """
    id: str = Field(..., description="Unique recommendation identifier")
    resource_id: str = Field(..., description="ID of the target resource")
    resource_type: str = Field(..., description="Service type: EC2, S3, EBS, RDS")
    title: str = Field(..., description="Short recommendation title")
    reason: str = Field(..., description="Technical justification for the recommendation")
    risk: RiskLevel = Field(..., description="Risk classification")
    confidence: ConfidenceScore = Field(..., description="Confidence score")
    monthly_savings: float = Field(..., ge=0, description="Estimated monthly savings ($)")
    annual_savings: float = Field(..., ge=0, description="Estimated annual savings ($)")
    implementation_steps: List[str] = Field(
        default_factory=list,
        description="Ordered implementation steps"
    )
    executive_explanation: str = Field(
        ...,
        description="Business-friendly explanation for executives"
    )
    category: Optional[RecommendationCategory] = Field(
        default=None,
        description="Quick Win / High Impact / Strategic"
    )
    rule_id: str = Field(..., description="Source rule ID (e.g., EC2-001)")


# ---------------------------------------------------------------------------
# Savings Summary — Recommendation-Rules.md §8–9
# ---------------------------------------------------------------------------

class SavingsSummary(BaseModel):
    """Aggregated savings across all recommendations.

    Formulas (per Recommendation-Rules.md §8):
        monthly_savings = current_monthly_cost - optimized_monthly_cost
        annual_savings  = monthly_savings * 12
        roi_percentage  = (annual_savings / implementation_cost) * 100

    Attributes:
        total_monthly_savings:        Sum of all monthly savings.
        total_annual_savings:         Sum of all annual savings.
        roi_percentage:               Return on investment percentage.
        total_current_monthly_cost:   Sum of current costs across all resources.
        savings_percentage:           Savings as percentage of current spend.
        recommendations_count:        Total number of recommendations.
        recommendations_by_category:  Count by category.
        recommendations_by_risk:      Count by risk level.
        recommendations_by_service:   Count by service type.
    """
    total_monthly_savings: float = Field(default=0.0, description="Total monthly savings ($)")
    total_annual_savings: float = Field(default=0.0, description="Total annual savings ($)")
    roi_percentage: float = Field(default=0.0, description="ROI percentage")
    total_current_monthly_cost: float = Field(default=0.0, description="Current total monthly cost ($)")
    savings_percentage: float = Field(default=0.0, description="Savings as % of current spend")
    recommendations_count: int = Field(default=0, description="Total recommendations")
    recommendations_by_category: Dict[str, int] = Field(
        default_factory=dict,
        description="Recommendation count by category"
    )
    recommendations_by_risk: Dict[str, int] = Field(
        default_factory=dict,
        description="Recommendation count by risk level"
    )
    recommendations_by_service: Dict[str, int] = Field(
        default_factory=dict,
        description="Recommendation count by service type"
    )


# ---------------------------------------------------------------------------
# Forecast Result — API-Specification.yaml (ForecastResponse)
# ---------------------------------------------------------------------------

class ForecastResult(BaseModel):
    """Prophet-based cost forecast result.

    Mandatory outputs (per Recommendation-Rules.md §13):
        - Next month forecast
        - Three-month forecast
        - Confidence intervals
        - Growth percentages
        - Executive explanations
        - Seasonality detection

    The forecast model is ALWAYS Meta Prophet.
    Linear regression, moving averages, and manual extrapolation
    are explicitly prohibited.
    """
    model: str = Field(default="Prophet", description="Forecasting model (always Prophet)")
    next_month: float = Field(..., description="Predicted cost for next month ($)")
    three_month_forecast: List[float] = Field(
        ...,
        description="Array of 3 monthly predicted costs ($)"
    )
    growth_rate: float = Field(..., description="Projected growth rate (%)")
    confidence_interval: Dict[str, float] = Field(
        ...,
        description="Confidence interval: {lower, upper}"
    )
    seasonality_detected: bool = Field(..., description="Whether seasonality was detected")
    executive_summary: str = Field(..., description="Business-friendly forecast explanation")
    trend_direction: str = Field(
        default="increasing",
        description="Trend direction: increasing, decreasing, stable"
    )
    historical_data_points: int = Field(
        default=0,
        description="Number of historical data points used"
    )


# ---------------------------------------------------------------------------
# FinOps Score Result — API-Specification.yaml (ScoreResponse)
# ---------------------------------------------------------------------------

class ScoreBreakdown(BaseModel):
    """Breakdown of the FinOps score by domain.

    Attributes:
        compute:           Compute efficiency sub-score.
        storage:           Storage efficiency sub-score.
        reserved_capacity: Reserved capacity adoption sub-score.
    """
    compute: int = Field(default=0, description="Compute efficiency sub-score")
    storage: int = Field(default=0, description="Storage efficiency sub-score")
    reserved_capacity: int = Field(default=0, description="Reserved capacity sub-score")


class ScorePenalty(BaseModel):
    """A single penalty or reward applied to the FinOps score."""
    condition: str = Field(..., description="Condition that triggered the penalty/reward")
    points: int = Field(..., description="Points added (positive) or deducted (negative)")
    details: str = Field(default="", description="Additional context")


class ScoreResult(BaseModel):
    """Cloud Efficiency Score (FinOps Score) result.

    Score range: 0–100 (per Recommendation-Rules.md §11)

    Categories:
        90–100: Excellent
        70–89:  Healthy
        50–69:  Needs Optimization
        Below 50: Critical

    Starting score is 100, then penalties and rewards are applied.
    """
    score: int = Field(..., ge=0, le=100, description="Cloud Efficiency Score (0–100)")
    category: str = Field(..., description="Score category")
    breakdown: ScoreBreakdown = Field(
        default_factory=ScoreBreakdown,
        description="Score breakdown by domain"
    )
    penalties: List[ScorePenalty] = Field(
        default_factory=list,
        description="Applied penalties"
    )
    rewards: List[ScorePenalty] = Field(
        default_factory=list,
        description="Applied rewards"
    )
    recommendations: List[str] = Field(
        default_factory=list,
        description="Score improvement recommendations"
    )


# ---------------------------------------------------------------------------
# Analytics Pipeline Result — Aggregated output from main.py
# ---------------------------------------------------------------------------

class AnalyticsResult(BaseModel):
    """Complete analytics pipeline output.

    Contains all results from the analytics pipeline execution,
    structured for serialization to results.json and consumption
    by the backend API layer.
    """
    recommendations: List[Recommendation] = Field(
        default_factory=list,
        description="All optimization recommendations"
    )
    savings: SavingsSummary = Field(
        default_factory=SavingsSummary,
        description="Aggregated savings summary"
    )
    score: ScoreResult = Field(
        ...,
        description="FinOps health score"
    )
    forecast: Optional[ForecastResult] = Field(
        default=None,
        description="Prophet forecast results"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Pipeline execution metadata"
    )
